import type { Prisma } from '@prisma/client';
import type { ImageProofType, PaymentMethod } from '@potato-corner/shared';
import { prisma } from '../../lib/prisma.js';
import { resolveDateRangeBoundary } from '../../lib/manila-time.js';
import type { TransactionListFilters } from './transactions.types.js';
import type { DiscountAuditFilters } from './transactions.types.js';

const transactionInclude = {
  items: true,
  shift: { select: { id: true, status: true, branchId: true } },
} satisfies Prisma.TransactionInclude;

const holdOrderInclude = {
  items: true,
} satisfies Prisma.HoldOrderInclude;

/** Task 93 — sale-time snapshot of one selected Product Option for a transaction line. */
export interface SelectedOptionSnapshot {
  optionId: string;
  optionName: string;
  optionGroupId: string;
  optionGroupName: string;
  priceAdjustment: number;
}

interface CreateHoldOrderRow {
  branchId: string;
  shiftId: string;
  cashierId: string;
  expiresAt: Date;
  items: {
    productId: string;
    productVariantId: string;
    flavorId: string | null;
    productName: string;
    variantName: string;
    flavorName: string | null;
    unitPrice: number;
    quantity: number;
  }[];
}

interface CreateTransactionRow {
  branchId: string;
  shiftId: string;
  cashierId: string;
  receiptNumber: string;
  paymentMethod: PaymentMethod;
  subtotal: number;
  discountAmount: number;
  discountType: string | null;
  discountCustomerIdEncrypted: string | null;
  discountCustomerIdHash: string | null;
  vatAmount: number;
  vatExemptAmount: number;
  totalAmount: number;
  cashTendered: number | null;
  changeAmount: number | null;
  gcashReference: string | null;
  gcashManuallyVerified: boolean | null;
  paymentProofKey: string | null;
  paymentProofType: ImageProofType | null;
  paymentProofUploadedAt: Date | null;
  discountProofKey: string | null;
  discountProofType: ImageProofType | null;
  discountProofUploadedAt: Date | null;
  isOfflineTransaction: boolean;
  offlineProvisionalNumber: string | null;
  deviceId: string | null;
  items: {
    // Pre-generated by the service layer. Optional for backward
    // compatibility with existing callers/tests — Prisma falls back to its
    // own default(uuid()) when omitted.
    id?: string;
    productId: string;
    productVariantId: string;
    flavorId: string | null;
    productName: string;
    variantName: string;
    flavorName: string | null;
    unitPrice: number;
    quantity: number;
    lineTotal: number;
    recipeVersion: number;
    deductionSnapshot?: { inventoryItemId: string; quantity: number; baseUnitId: string }[];
    selectedFlavors?: { slotIndex: number; snackProductVariantId: string; flavorId: string }[] | null;
    selectedOptions?: SelectedOptionSnapshot[] | null;
  }[];
}

function buildListWhere(filters: TransactionListFilters): Prisma.TransactionWhereInput {
  return {
    ...(filters.branchId && { branchId: filters.branchId }),
    ...(filters.shiftId && { shiftId: filters.shiftId }),
    ...(filters.status && { status: filters.status }),
    ...(filters.paymentMethod && { paymentMethod: filters.paymentMethod }),
    ...((filters.dateFrom || filters.dateTo) && {
      createdAt: {
        // dateFrom/dateTo are bare Manila business dates (YYYY-MM-DD) —
        // `${value}T00:00:00.000Z` anchors to Manila 8:00 AM, not Manila
        // midnight, dropping that morning's transactions.
        ...(filters.dateFrom && { gte: resolveDateRangeBoundary(filters.dateFrom, 'start') }),
        ...(filters.dateTo && { lte: resolveDateRangeBoundary(filters.dateTo, 'end') }),
      },
    }),
  };
}

/**
 * Transactions repository. All Prisma calls for this module live here — the
 * router and service layers never call Prisma directly.
 */
export const transactionsRepository = {
  findDiscountAuditTrail(filters: DiscountAuditFilters) {
    const where: Prisma.TransactionWhereInput = {
      discountType: { not: null },
      ...(filters.branchIds !== 'all' ? { branchId: { in: filters.branchIds } } : {}),
      ...(filters.discountType ? { discountType: filters.discountType } : {}),
      ...(filters.dateFrom || filters.dateTo
        ? {
            createdAt: {
              ...(filters.dateFrom ? { gte: resolveDateRangeBoundary(filters.dateFrom, 'start') } : {}),
              ...(filters.dateTo ? { lte: resolveDateRangeBoundary(filters.dateTo, 'end') } : {}),
            },
          }
        : {}),
    };
    return Promise.all([
      prisma.transaction.findMany({
        where,
        select: {
          id: true,
          branchId: true,
          transactionNumber: true,
          cashierId: true,
          discountType: true,
          discountAmount: true,
          discountCustomerIdEncrypted: true,
          discountCustomerIdHash: true,
          // Task 209.16 — existence flag + capture mode for the Discount
          // Compliance report's Proof Available/View Proof column, same
          // has_discount_proof pattern toTransactionResponse already uses
          // elsewhere. The signed URL itself is still only ever fetched
          // lazily via GET /:transactionId/discount-proof, never from here.
          discountProofKey: true,
          discountProofType: true,
          createdAt: true,
        },
        orderBy: { createdAt: 'desc' },
        skip: (filters.page - 1) * filters.limit,
        take: filters.limit,
      }),
      prisma.transaction.count({ where }),
    ]).then(([rows, total]) => ({ rows, total }));
  },

  findBranch(branchId: string) {
    return prisma.branch.findUnique({ where: { id: branchId }, select: { id: true, code: true, status: true } });
  },

  /** Batch lookup for cart pricing/validation — one query for every distinct variant in the cart. */
  findVariantsForSale(variantIds: string[]) {
    return prisma.productVariant.findMany({
      where: { id: { in: variantIds } },
      include: {
        product: { select: { id: true, name: true, status: true } },
        variantFlavors: { include: { flavor: { select: { id: true, name: true, isActive: true } } } },
        // CR-008 Product Options (Task 32) — the trusted, DB-sourced set of
        // options this variant is actually allowed to sell, used to price
        // and validate selectedOptionIds server-side. Never trust a
        // frontend-provided option name/price for this. Also fetches the
        // option group's own `options` list (Task 105) — an assignment with
        // no allowedOptions rows means "all active options in the group"
        // (CR-008 R11/R12, same fallback getPosCatalog's option_groups
        // mapping applies), so checkout validation must see the same set
        // the POS terminal rendered as selectable, or it rejects options the
        // POS itself offered.
        optionGroupAssignments: {
          include: {
            optionGroup: {
              select: {
                id: true,
                name: true,
                posButtonLabel: true,
                options: {
                  where: { isActive: true },
                  select: { id: true, name: true, isActive: true, priceAdjustment: true },
                },
              },
            },
            allowedOptions: {
              include: {
                productOption: { select: { id: true, name: true, isActive: true, priceAdjustment: true } },
              },
            },
          },
        },
        flavorSlots: {
          orderBy: { slotIndex: 'asc' },
          include: {
            snackOptions: {
              include: {
                snackProductVariant: {
                  select: {
                    id: true,
                    isActive: true,
                    product: { select: { id: true, status: true } },
                    variantFlavors: { include: { flavor: { select: { id: true, name: true, isActive: true } } } },
                  },
                },
              },
            },
          },
        },
      },
    });
  },

  findBranchProductAvailabilityMap(branchId: string, productIds: string[]) {
    return prisma.branchProductAvailability.findMany({
      where: { branchId, productId: { in: productIds } },
      select: { productId: true, isAvailable: true },
    });
  },

  findBranchFlavorAvailabilityMap(branchId: string, flavorIds: string[]) {
    return prisma.branchFlavorAvailability.findMany({
      where: { branchId, flavorId: { in: flavorIds } },
      select: { flavorId: true, isAvailable: true },
    });
  },

  /**
   * Product Option inventory deduction (Task 79) — ProductOptionInventoryMapping
   * is the source of truth, replacing the legacy ProductComponent.productOptionId
   * rows. One mapping per option (productOptionId is @unique on the mapping),
   * so an option with no row here simply has nothing to deduct.
   */
  findOptionInventoryMappings(optionIds: string[]) {
    return prisma.productOptionInventoryMapping.findMany({
      where: { productOptionId: { in: optionIds } },
      select: {
        productOptionId: true,
        inventoryItemId: true,
        quantityRequired: true,
        deductionUnitId: true,
        inventoryItem: { select: { baseUnitId: true, deletedAt: true } },
      },
    });
  },

  /**
   * Transaction row + its line items are created atomically — a crash
   * partway through must never leave a transaction with zero items. Written
   * as a single nested-create call (items created inline, response included
   * in the same round trip) rather than create + createMany + a separate
   * re-fetch — the re-fetch was reading back data this same call had just
   * written, one avoidable round trip inside the POS checkout's interactive
   * transaction (see transactions.service.ts createTransaction).
   */
  async createTransaction(data: CreateTransactionRow, tx?: Prisma.TransactionClient) {
    const run = (client: Prisma.TransactionClient) =>
      client.transaction.create({
        data: {
          branchId: data.branchId,
          shiftId: data.shiftId,
          cashierId: data.cashierId,
          transactionNumber: data.receiptNumber,
          paymentMethod: data.paymentMethod,
          subtotal: data.subtotal,
          discountAmount: data.discountAmount,
          discountType: data.discountType,
          discountCustomerIdEncrypted: data.discountCustomerIdEncrypted,
          discountCustomerIdHash: data.discountCustomerIdHash,
          vatAmount: data.vatAmount,
          vatExemptAmount: data.vatExemptAmount,
          totalAmount: data.totalAmount,
          amountTendered: data.cashTendered,
          changeAmount: data.changeAmount,
          gcashReference: data.gcashReference,
          gcashManuallyVerified: data.gcashManuallyVerified,
          paymentProofKey: data.paymentProofKey,
          paymentProofType: data.paymentProofType,
          paymentProofUploadedAt: data.paymentProofUploadedAt,
          discountProofKey: data.discountProofKey,
          discountProofType: data.discountProofType,
          discountProofUploadedAt: data.discountProofUploadedAt,
          isOfflineTransaction: data.isOfflineTransaction,
          offlineProvisionalNumber: data.offlineProvisionalNumber,
          deviceId: data.deviceId,
          items: {
            create: data.items.map((item) => ({
              id: item.id,
              productId: item.productId,
              productVariantId: item.productVariantId,
              flavorId: item.flavorId,
              productNameSnapshot: item.productName,
              variantNameSnapshot: item.variantName,
              flavorNameSnapshot: item.flavorName,
              unitPriceSnapshot: item.unitPrice,
              quantity: item.quantity,
              lineTotal: item.lineTotal,
              recipeVersion: item.recipeVersion,
              deductionSnapshot: item.deductionSnapshot,
              selectedFlavors: item.selectedFlavors ?? undefined,
              // Cast needed: SelectedOptionSnapshot is a named interface, and Prisma's
              // InputJsonValue union requires structural index-signature compatibility
              // that named interfaces don't structurally satisfy on their own (unlike the
              // inline object-literal types used by selectedFlavors/deductionSnapshot
              // above) -- the values are plain JSON-serializable objects either way.
              selectedOptions: (item.selectedOptions ?? undefined) as Prisma.InputJsonValue | undefined,
            })),
          },
        },
        include: transactionInclude,
      });
    if (tx) return run(tx);
    return prisma.$transaction(run);
  },

  findTransactionById(id: string) {
    return prisma.transaction.findUnique({ where: { id }, include: transactionInclude });
  },

  /**
   * Idempotent-replay guard for offline sync: fast-path lookup-before-insert
   * against the same (branchId, deviceId, offlineProvisionalNumber) triple
   * the transactions_branch_device_offline_number_key unique index (Task
   * 209.47) enforces at the DB level. This lookup alone is best-effort under
   * true concurrent replays (two requests can both miss here before either
   * inserts) — the unique index is the actual concurrency authority; see
   * isOfflineSyncUniqueConflict / syncOfflineTransactions for the race path.
   * All three arguments are non-null whenever this is called — a query
   * with a null deviceId or offlineProvisionalNumber would match on Prisma's
   * `equals: null`, which is exactly the legacy/online rows this must never
   * match.
   */
  findByOfflineIdentity(branchId: string, deviceId: string, offlineProvisionalNumber: string) {
    return prisma.transaction.findFirst({
      where: { branchId, deviceId, offlineProvisionalNumber },
      include: transactionInclude,
    });
  },

  async listTransactions(filters: TransactionListFilters) {
    const where = buildListWhere(filters);
    const [transactions, total] = await Promise.all([
      prisma.transaction.findMany({
        where,
        include: transactionInclude,
        orderBy: { createdAt: 'desc' },
        skip: (filters.page - 1) * filters.limit,
        take: filters.limit,
      }),
      prisma.transaction.count({ where }),
    ]);
    return { transactions, total };
  },

  voidTransaction(id: string, data: { voidedById: string; voidReason: string }, tx?: Prisma.TransactionClient) {
    const client = tx ?? prisma;
    return client.transaction.update({
      where: { id },
      data: { status: 'voided', voidedAt: new Date(), voidedById: data.voidedById, voidReason: data.voidReason },
      include: transactionInclude,
    });
  },

  refundTransaction(id: string, data: { refundedById: string; refundReason: string }, tx?: Prisma.TransactionClient) {
    const client = tx ?? prisma;
    return client.transaction.update({
      where: { id },
      data: { status: 'refunded', refundedAt: new Date(), refundedById: data.refundedById, refundReason: data.refundReason },
      include: transactionInclude,
    });
  },

  markReceiptPrinted(id: string) {
    return prisma.transaction.update({ where: { id }, data: { receiptPrinted: true }, include: transactionInclude });
  },

  /**
   * One row per shift closed inside [dayStart, dayEnd], with its voided
   * transactions and its discounted-and-completed transactions. Backs
   * fraud rules 1 (excessive voids), 2 (discount abuse), 6 (end of shift
   * void), and 7 (employee self-discount frequency) — each rule filters
   * this same shape differently rather than four near-duplicate queries.
   */
  findClosedShiftTransactionSummaries(branchId: string, dayStart: Date, dayEnd: Date) {
    return prisma.shift.findMany({
      where: { branchId, status: { in: ['closed', 'flagged'] }, closedAt: { gte: dayStart, lte: dayEnd } },
      select: {
        id: true,
        cashierId: true,
        closedAt: true,
        transactions: {
          where: { OR: [{ status: 'voided' }, { status: 'completed', discountType: { not: null } }] },
          select: { id: true, status: true, discountType: true, voidedAt: true },
        },
      },
    });
  },

  /** Per-cashier GCash transaction count for one day — the "actual" side of rule 4's anomaly comparison. */
  async findGcashCountsByCashierForDate(branchId: string, dayStart: Date, dayEnd: Date) {
    const rows = await prisma.transaction.groupBy({
      by: ['cashierId'],
      where: { branchId, paymentMethod: 'gcash', status: 'completed', createdAt: { gte: dayStart, lte: dayEnd } },
      _count: { _all: true },
    });
    return rows.map((row) => ({ cashierId: row.cashierId, gcashCount: row._count._all }));
  },

  /** Total branch-wide GCash transaction count over a trailing window — the denominator for rule 4's daily average. */
  countGcashTransactionsForBranchWindow(branchId: string, windowStart: Date, windowEnd: Date) {
    return prisma.transaction.count({
      where: { branchId, paymentMethod: 'gcash', status: 'completed', createdAt: { gte: windowStart, lte: windowEnd } },
    });
  },

  /** Every statutory-discount transaction with a hash in the trailing window, across all branches — rule 5 groups these by hash itself (Corrections #4: this rule is global-scope, not per-branch). */
  findStatutoryDiscountsInWindow(windowStart: Date, windowEnd: Date) {
    return prisma.transaction.findMany({
      where: {
        status: 'completed',
        discountType: { in: ['pwd', 'senior_citizen'] },
        discountCustomerIdHash: { not: null },
        createdAt: { gte: windowStart, lte: windowEnd },
      },
      select: { id: true, branchId: true, cashierId: true, discountCustomerIdHash: true, createdAt: true },
    });
  },

  /** 3-per-terminal limit (Architecture doc §Part 8) — "terminal" mapped to active shift, see transactions.types.ts. */
  countActiveHoldOrdersForShift(shiftId: string) {
    return prisma.holdOrder.count({ where: { shiftId, status: 'held' } });
  },

  async createHoldOrder(data: CreateHoldOrderRow) {
    return prisma.$transaction(async (tx) => {
      const holdOrder = await tx.holdOrder.create({
        data: {
          branchId: data.branchId,
          shiftId: data.shiftId,
          cashierId: data.cashierId,
          expiresAt: data.expiresAt,
        },
      });

      await tx.holdOrderItem.createMany({
        data: data.items.map((item) => ({
          holdOrderId: holdOrder.id,
          productId: item.productId,
          productVariantId: item.productVariantId,
          flavorId: item.flavorId,
          productNameSnapshot: item.productName,
          variantNameSnapshot: item.variantName,
          flavorNameSnapshot: item.flavorName,
          unitPriceSnapshot: item.unitPrice,
          quantity: item.quantity,
        })),
      });

      return tx.holdOrder.findUniqueOrThrow({ where: { id: holdOrder.id }, include: holdOrderInclude });
    });
  },

  findHoldOrderById(id: string) {
    return prisma.holdOrder.findUnique({ where: { id }, include: holdOrderInclude });
  },

  listActiveHoldOrdersForShift(shiftId: string) {
    return prisma.holdOrder.findMany({
      where: { shiftId, status: 'held' },
      include: holdOrderInclude,
      orderBy: { createdAt: 'asc' },
    });
  },

  releaseHoldOrder(id: string) {
    return prisma.holdOrder.update({
      where: { id },
      data: { status: 'released', releasedAt: new Date() },
      include: holdOrderInclude,
    });
  },

  /**
   * Only transitions rows still `held` — a hold already released between the
   * expiry job firing and this write must not be overwritten back to
   * `expired`. Returns the updated count so the worker can tell a genuine
   * expiry apart from a harmless no-op race against a concurrent release.
   */
  expireHoldOrderIfStillHeld(id: string) {
    return prisma.holdOrder.updateMany({
      where: { id, status: 'held' },
      data: { status: 'expired', expiredAt: new Date() },
    });
  },
};
